/*
 * This file is generated by jOOQ.
 */
package net.codeer.app.multiSchemaLevel.jooq.tables.records;


import java.time.LocalDateTime;

import net.codeer.app.multiSchemaLevel.jooq.tables.Todos;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TodosRecord extends UpdatableRecordImpl<TodosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.todos.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.todos.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.todos.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.todos.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.todos.done</code>.
     */
    public void setDone(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.todos.done</code>.
     */
    public Boolean getDone() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.todos.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.todos.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.todos.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.todos.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TodosRecord
     */
    public TodosRecord() {
        super(Todos.TODOS);
    }

    /**
     * Create a detached, initialised TodosRecord
     */
    public TodosRecord(String id, String content, Boolean done, LocalDateTime created, String createdBy) {
        super(Todos.TODOS);

        setId(id);
        setContent(content);
        setDone(done);
        setCreated(created);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }
}
