/*
 * This file is generated by jOOQ.
 */
package net.codeer.app.multiSchemaLevel.jooq;


import net.codeer.app.multiSchemaLevel.jooq.tables.Todos;
import net.codeer.app.multiSchemaLevel.jooq.tables.records.TodosRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TodosRecord> TODOS_PKEY = Internal.createUniqueKey(Todos.TODOS, DSL.name("todos_pkey"), new TableField[] { Todos.TODOS.ID }, true);
}
