/*
 * This file is generated by jOOQ.
 */
package net.codeer.app.multiSchemaLevel.jooq;


import net.codeer.app.multiSchemaLevel.jooq.tables.Todos;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.todos</code>.
     */
    public static final Todos TODOS = Todos.TODOS;
}
