/*
 * This file is generated by jOOQ.
 */
package net.codeer.app.multiSchemaLevel.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import net.codeer.app.multiSchemaLevel.jooq.Indexes;
import net.codeer.app.multiSchemaLevel.jooq.Keys;
import net.codeer.app.multiSchemaLevel.jooq.Public;
import net.codeer.app.multiSchemaLevel.jooq.tables.records.TodosRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Todos extends TableImpl<TodosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.todos</code>
     */
    public static final Todos TODOS = new Todos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TodosRecord> getRecordType() {
        return TodosRecord.class;
    }

    /**
     * The column <code>public.todos.id</code>.
     */
    public final TableField<TodosRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.todos.content</code>.
     */
    public final TableField<TodosRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.todos.done</code>.
     */
    public final TableField<TodosRecord, Boolean> DONE = createField(DSL.name("done"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.todos.created</code>.
     */
    public final TableField<TodosRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.todos.created_by</code>.
     */
    public final TableField<TodosRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Todos(Name alias, Table<TodosRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Todos(Name alias, Table<TodosRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.todos</code> table reference
     */
    public Todos(String alias) {
        this(DSL.name(alias), TODOS);
    }

    /**
     * Create an aliased <code>public.todos</code> table reference
     */
    public Todos(Name alias) {
        this(alias, TODOS);
    }

    /**
     * Create a <code>public.todos</code> table reference
     */
    public Todos() {
        this(DSL.name("todos"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_TODO_CREATED, Indexes.IDX_TODO_CREATED_BY);
    }

    @Override
    public UniqueKey<TodosRecord> getPrimaryKey() {
        return Keys.TODOS_PKEY;
    }

    @Override
    public Todos as(String alias) {
        return new Todos(DSL.name(alias), this);
    }

    @Override
    public Todos as(Name alias) {
        return new Todos(alias, this);
    }

    @Override
    public Todos as(Table<?> alias) {
        return new Todos(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Todos rename(String name) {
        return new Todos(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Todos rename(Name name) {
        return new Todos(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Todos rename(Table<?> name) {
        return new Todos(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todos where(Condition condition) {
        return new Todos(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todos where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todos where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todos where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Todos where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Todos where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Todos where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Todos where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todos whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todos whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
