/*
 * This file is generated by jOOQ.
 */
package net.codeer.app.single.jooq;


import net.codeer.app.single.jooq.tables.Todos;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_TODO_CREATED = Internal.createIndex(DSL.name("idx_todo_created"), Todos.TODOS, new OrderField[] { Todos.TODOS.CREATED.desc() }, false);
    public static final Index IDX_TODO_CREATED_BY = Internal.createIndex(DSL.name("idx_todo_created_by"), Todos.TODOS, new OrderField[] { Todos.TODOS.CREATED_BY }, false);
}
